# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(b8e8ae43-2573-4f7f-967c-0f08a892e692)'
    subscriptionId: 'b8e8ae43-2573-4f7f-967c-0f08a892e692'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'premierDeploiementrg'
    location: 'Canada East'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
